version: '3.1'

services:
  arch_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arch_gateway
    ports:
      - "8186:5228"
    volumes:
      - arch_data:/app/data
    restart: always
    environment:
      - CLERK_URL=https://localhost:5140/clerk
      - APM_URL=http://localhost:8200
    networks:
      - my_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5228/health" ]
      interval: 60s
      timeout: 20s
      retries: 3

networks:
  my_network:

volumes:
  arch_data: