// <auto-generated />
using System;
using Data.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Sql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230122110008_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Domains.EndpointDefinition", b =>
                {
                    b.Property<string>("Pattern")
                        .HasColumnType("text");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<Guid?>("ServiceConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Pattern");

                    b.HasIndex("ServiceConfigId");

                    b.ToTable("endpoint_definitions", (string)null);
                });

            modelBuilder.Entity("Core.Domains.Meta", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("EndpointDefinitionPattern")
                        .HasColumnType("text");

                    b.Property<Guid?>("ServiceConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("EndpointDefinitionPattern");

                    b.HasIndex("ServiceConfigId");

                    b.ToTable("meta", (string)null);
                });

            modelBuilder.Entity("Core.Domains.ServiceConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("service_configs", (string)null);
                });

            modelBuilder.Entity("Core.Domains.EndpointDefinition", b =>
                {
                    b.HasOne("Core.Domains.ServiceConfig", null)
                        .WithMany("EndpointDefinitions")
                        .HasForeignKey("ServiceConfigId");
                });

            modelBuilder.Entity("Core.Domains.Meta", b =>
                {
                    b.HasOne("Core.Domains.EndpointDefinition", null)
                        .WithMany("Meta")
                        .HasForeignKey("EndpointDefinitionPattern");

                    b.HasOne("Core.Domains.ServiceConfig", null)
                        .WithMany("Meta")
                        .HasForeignKey("ServiceConfigId");
                });

            modelBuilder.Entity("Core.Domains.EndpointDefinition", b =>
                {
                    b.Navigation("Meta");
                });

            modelBuilder.Entity("Core.Domains.ServiceConfig", b =>
                {
                    b.Navigation("EndpointDefinitions");

                    b.Navigation("Meta");
                });
#pragma warning restore 612, 618
        }
    }
}
