// <auto-generated />
using System;
using Data.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Sql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.EndpointDefinitions.EndpointDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pattern");

                    b.Property<Guid?>("ServiceConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceConfigId");

                    b.ToTable("endpoint_definitions", (string)null);
                });

            modelBuilder.Entity("Core.Metas.Meta", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<Guid?>("EndpointDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ServiceConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("EndpointDefinitionId");

                    b.HasIndex("ServiceConfigId");

                    b.ToTable("meta", (string)null);
                });

            modelBuilder.Entity("Core.ServiceConfigs.ServiceConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("service_configs", (string)null);
                });

            modelBuilder.Entity("Core.EndpointDefinitions.EndpointDefinition", b =>
                {
                    b.HasOne("Core.ServiceConfigs.ServiceConfig", null)
                        .WithMany("EndpointDefinitions")
                        .HasForeignKey("ServiceConfigId");
                });

            modelBuilder.Entity("Core.Metas.Meta", b =>
                {
                    b.HasOne("Core.EndpointDefinitions.EndpointDefinition", null)
                        .WithMany("Meta")
                        .HasForeignKey("EndpointDefinitionId");

                    b.HasOne("Core.ServiceConfigs.ServiceConfig", null)
                        .WithMany("Meta")
                        .HasForeignKey("ServiceConfigId");
                });

            modelBuilder.Entity("Core.EndpointDefinitions.EndpointDefinition", b =>
                {
                    b.Navigation("Meta");
                });

            modelBuilder.Entity("Core.ServiceConfigs.ServiceConfig", b =>
                {
                    b.Navigation("EndpointDefinitions");

                    b.Navigation("Meta");
                });
#pragma warning restore 612, 618
        }
    }
}
