<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Arch.Core</RootNamespace>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>Arch.Gateway.Core</PackageId>
        <Version>0.9.2</Version>
        <Authors>Plumber</Authors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DotNetCore.CAP" Version="10.0.1" />
        <PackageReference Include="FastEndpoints" Version="8.1.0" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Arch" />
    </ItemGroup>

</Project>
