// <auto-generated />
using System;
using Arch.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Arch.Data.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Arch.Core.ServiceConfigs.EndpointDefinitions.EndpointDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("MapTo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("map_to");

                    b.Property<string>("Meta")
                        .HasColumnType("text")
                        .HasColumnName("meta");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pattern");

                    b.Property<Guid>("service_config_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint");

                    b.HasIndex("MapTo");

                    b.HasIndex("Pattern");

                    b.HasIndex("service_config_id");

                    b.ToTable("endpoint_definitions", (string)null);
                });

            modelBuilder.Entity("Arch.Core.ServiceConfigs.ServiceConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrls")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_urls");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Meta")
                        .HasColumnType("text")
                        .HasColumnName("meta");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Primary")
                        .HasColumnType("boolean")
                        .HasColumnName("primary");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("service_configs", (string)null);
                });

            modelBuilder.Entity("Arch.Core.ServiceConfigs.EndpointDefinitions.EndpointDefinition", b =>
                {
                    b.HasOne("Arch.Core.ServiceConfigs.ServiceConfig", "ServiceConfig")
                        .WithMany("EndpointDefinitions")
                        .HasForeignKey("service_config_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceConfig");
                });

            modelBuilder.Entity("Arch.Core.ServiceConfigs.ServiceConfig", b =>
                {
                    b.Navigation("EndpointDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
